<a href="https://colab.research.google.com/github/sachinthadilshann/TensorFlow-and-Deep-Learning-fundamentals-with-Python-by-Daniel-Bourke-/blob/main/00_tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

print(tf.__version__)

In [ ]:
 scalar = tf.constant(7)
 scalar

In [ ]:
#check #of  dimensions
scalar.ndim

In [ ]:
#crete vector
vector = tf.constant([10,10])
vector

In [ ]:
# # dimensions of a tensor
vector.ndim

In [ ]:
metrix = tf.constant([[10,7],
                      [5,10]])
metrix

In [ ]:
print(metrix.ndim)

In [ ]:
another_metrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16)
another_metrix

In [ ]:
another_metrix.ndim

In [ ]:
tensor = tf.constant([[[1,2,3],
                     [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [16,17,18]]])
tensor

In [ ]:
tensor.ndim

In [ ]:
tf.Variable

In [ ]:
changeable_tensor = tf.Variable([10,5])
unchangeable_tensor = tf.constant([10,5])
changeable_tensor,unchangeable_tensor

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor


In [ ]:
#random tensor
rabdom_1 = tf.random.Generator.from_seed(42)
rabdom_1 = rabdom_1.normal(shape=(3,2))
rabdom_2 = tf.random.Generator.from_seed(42)
rabdom_2 = rabdom_2.normal(shape=(3,2))
rabdom_1,rabdom_2,rabdom_1==rabdom_2

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,8]])
not_shuffled

In [ ]:
not_shuffled.ndim

In [ ]:
#shuffle the not shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled)

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

In [ ]:
tf.random.shuffle(not_shuffled,seed=42)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

Other way to create tensor

In [ ]:
 tf.ones([10,7])

In [ ]:
tf.zeros(shape=(3,4))

Turn Numpy arry into tensor

In [ ]:
#numpy tensor

import numpy as np

numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A

In [115]:
2*3*4

24

In [116]:
A = tf.constant(numpy_A,shape=(2,3,4))
B = tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [117]:
6*2*2

24

In [118]:
C = tf.constant(numpy_A,shape=(6,2,2))
D= tf.constant(numpy_A)
C,D

(<tf.Tensor: shape=(6, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20]],
 
        [[21, 22],
         [23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [119]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [120]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [121]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [122]:
2*3*4*5

120

In [123]:
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Element along the 0 axis: ",rank_4_tensor.shape[0])
print("Element along the last axis:",rank_4_tensor.shape[-1])
print("Total number of element our tensor:",tf.size(rank_4_tensor))
print("Total number of element our tensor:",tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Element along the 0 axis:  2
Element along the last axis: 5
Total number of element our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of element our tensor: 120


In [124]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [125]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [126]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [127]:
rank_4_tensor[:1,:1,:1,]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [128]:
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [129]:
#create a rank 2 tensor

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [130]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [131]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [132]:
tf.expand_dims(rank_2_tensor,axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [133]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [134]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

# Tensor Operations

**Basic Operation**

In [135]:
tensor = tf.constant([[10,7],
 [3,4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [136]:
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [137]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [138]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [139]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [140]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

**Matrix Multiplication**

In [141]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [142]:
tensor,tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [143]:
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [144]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [145]:
tensor.shape

TensorShape([2, 2])

In [146]:
x = tf.constant([[1,2,2],
                [3,4,4],
                [5,6,5]])

y = tf.constant([[7,8],
                [9,10],
                [11,12]])

In [147]:
x , y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 2],
        [3, 4, 4],
        [5, 6, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [148]:
x@y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 47,  52],
       [101, 112],
       [144, 160]], dtype=int32)>

In [149]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 47,  52],
       [101, 112],
       [144, 160]], dtype=int32)>

In [150]:
a = tf.constant([[1,2],
                [3,4],
                [5,6]])

b = tf.constant([[7,8],
                [9,10],
                [11,12]])

In [151]:
tf.transpose(a)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [152]:
tf.matmul(tf.transpose(a),b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

# The dot product

In [153]:
tf.tensordot(tf.transpose(a),b,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [154]:
print("Normal A:")

print(a,'\n')

print('A reshaped')
print(tf.reshape(a,shape=(2,3)),'\n')

print('A transposed')
print(tf.transpose(a))

Normal A:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32) 

A reshaped
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32) 

A transposed
tf.Tensor(
[[1 3 5]
 [2 4 6]], shape=(2, 3), dtype=int32)


In [155]:
tf.matmul(a,tf.transpose(b))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

Changing Datatype

In [156]:
c = tf.constant([1.4,4.5])
c.dtype

tf.float32

In [157]:
d = tf.constant([3,5])
d.dtype

tf.int32

In [158]:
e = tf.cast(c,dtype=tf.float16)
e.dtype

tf.float16

**Aggregating Tensor**

In [159]:
d = tf.constant([-7,-10])
d

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [160]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [161]:
F = tf.constant(np.random.randint(0,100,size=50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([82, 44, 99, 62,  1, 11, 38, 80, 56, 75, 21,  4, 69, 93, 27, 95, 23,
       41, 16, 74, 53, 73, 65, 33, 74, 35, 31, 37, 91, 98, 35,  5, 68, 42,
        8, 73, 32, 10, 68, 74, 65, 28, 73, 70, 49, 95, 20, 27,  4,  9])>

In [162]:
tf.size(F),F.shape,F.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [163]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [164]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [165]:
tf.reduce_mean(F)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [166]:
tf.reduce_sum(F)

<tf.Tensor: shape=(), dtype=int64, numpy=2456>

In [167]:
import tensorflow_probability as tfp   #

tfp.stats.variance(F)

<tf.Tensor: shape=(), dtype=int64, numpy=849>

In [168]:
tf.math.reduce_std(tf.cast(F,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=29.14422>

In [169]:
tf.random.set_seed(42)
G = tf.random.uniform(shape=[50])
G

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [170]:
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [171]:
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [172]:
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [173]:
G[tf.argmax(G)] == tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [174]:
tf.argmin(G)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [175]:
G[tf.argmin(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [176]:
tf.random.set_seed(42)

H = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
H

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [177]:
H.shape

TensorShape([1, 1, 1, 1, 50])

In [178]:
H.ndim

5

In [179]:
G_squeezed = tf.squeeze(H)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [180]:
G_squeezed.shape

TensorShape([50])

# One-Hot Encoding

In [181]:
some_list = [0,1,2,3]

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [182]:
tf.one_hot(some_list,depth=4,on_value='2',off_value='4')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'2', b'4', b'4', b'4'],
       [b'4', b'2', b'4', b'4'],
       [b'4', b'4', b'2', b'4'],
       [b'4', b'4', b'4', b'2']], dtype=object)>

**Squaring, log, square root**

In [113]:
I = tf.range(1,10)
I

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [183]:
tf.square(I)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [184]:
tf.sqrt(tf.cast(I,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [185]:
tf.math.log(tf.cast(I,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
J = tf.constant(np.array)